// Autor: V M J  &  AL
// Date: 2024-11-06
// Description: Ablak objektum

// Az ablak objektum használata:
// Az ablak objektum a böngészőablakot reprezentálja, és számos tulajdonságot és metódust tartalmaz, amelyek segítségével kezelhetjük az ablakot.
// Az ablak objektum a globális objektumok egyike, tehát nem kell létrehoznunk, hogy használhassuk.
// Az ablak objektum a window változóban található, így a window.alert() ugyanazt jelenti, mint az alert().

// Az ablak objektum tulajdonságai...
// Az ablak objektum számos tulajdonságot tartalmaz, amelyek segítségével információkat szerezhetünk az ablakról.
// A leggyakrabban használt tulajdonságok a következők:

// Az orientáció zárolása portré módba.
function lockPortraitMode() {
    // Ellenőrizze, hogy a képernyő szélessége 768px-nél kisebb vagy egyenlő.
    if (window.innerWidth <= 768) {  // 768px az iPad szélessége...
        // Ha a kijelző szélessége nagyobb, mint a magassága (landscape mód), akkor:
            // Ellenőrizze, hogy az elem létezik-e, és ha nem, akkor jelenítse meg az elemet.
            // Az elem megjelenítése azért fontos, mert a felhasználó elforgatta a kijelzőt a portrait módba.
            // Ebben az esetben az elemet meg kell jeleníteni, mert a felhasználó nem tudja, hogy a kijelzőt elforgatták a landscape módba.
        if (window.innerWidth > window.innerHeight) {
            // Jelenítsünk meg egy üzenetet, ha a kijelzőt elforgatják a portré módba:
            let elem = document.getElementById("lockPortraitMessage");  // Az elem keresése...
            // Ha az elem nem létezik, akkor:
            if (!elem) {
                elem = document.createElement("div");                             // Az elem létrehozása...
                elem.id = "lockPortraitMessage";                                  // Az elem azonosítójának beállítása...
                elem.innerText = "Please turn the phone back to portrait mode.";  // Az elem szövegének beállítása...
                document.body.appendChild(elem);                                  // Az elem hozzáadása a dokumentumhoz...

                // Az elem stílusának beállítása:
                elem.style.display = "grid";                   // Az elem grid megjelenítése...
                elem.style.gridTemplateColumns = "1fr";        // Az elem oszlop sablon beállítása...
                elem.style.gridTemplateRows = "1fr";           // Az elem sor sablon beállítása...
                elem.style.justifyItems = "center";            // Az elem igazítása középre...
                elem.style.alignItems = "center";              // Az elem igazítása középre...

                elem.style.position = "fixed";                 // Az elem pozíciójának beállítása...
                elem.style.top = "0";                          // Az elem tetejének beállítása...
                elem.style.left = "0";                         // Az elem bal oldalának beállítása...
                elem.style.width = "100vw";                    // Az elem szélességének beállítása...
                elem.style.height = "100vh";                   // Az elem magasságának beállítása...
                elem.style.padding = "1rem";                   // Az elem belső margó beállítása...

                elem.style.backgroundColor = "palevioletred";  // Az elem háttérszínének beállítása...
                elem.style.color = "wheat";                    // Az elem szövegszínének beállítása...
                elem.style.fontSize = "3rem";                  // Az elem betűméretének beállítása...
                elem.style.zIndex = "1000";                    // Az elem z-index értékének beállítása...
            }
        }
        // Ha a kijelző szélessége kisebb, mint a magassága (portrait mód), akkor:
            // Ellenőrizze, hogy az elem létezik-e, és ha igen, távolítsa el az elemet.
            // Az elem eltávolítása azért fontos, mert a felhasználó visszaállította a kijelzőt a landscape módba.
            // Ebben az esetben az elemet már nem kell megjeleníteni.
            // Ha az elem nem létezik, akkor nincs mit tenni.
        else { 
            const elem = document.getElementById("lockPortraitMessage");  // Az elem keresése...
            if (elem) {                                                   // Ha az elem létezik, akkor...
                elem.remove();                                            // Az elem eltávolítása a dokumentumból...
            }
        }
    }
}

// Az esemény figyelése, amikor a képernyő mérete változik (pl. eszköz elforgatása).
    // Az esemény figyelése azért fontos, mert a felhasználó elforgatja a kijelzőt a landscape módba.
    // Ebben az esetben az elemet meg kell jeleníteni, mert a felhasználó nem tudja, hogy a kijelzőt elforgatták a portrait módba.
window.addEventListener("resize", lockPortraitMode);             // Az esemény figyelése...
window.addEventListener("orientationchange", lockPortraitMode);  // Az esemény figyelése...

// Az orientáció ellenőrzése betöltéskor is...
    // Az orientáció ellenőrzése azért fontos, mert a felhasználó betölti az oldalt, és az orientáció már a portré módban van.
    // Ebben az esetben az elemet meg kell jeleníteni, mert a felhasználó nem tudja, hogy a kijelzőt elforgatták a landscape módba.
lockPortraitMode();  // Az orientáció ellenőrzése...

// Az orientáció zárolása portré módba vége.